baseURL = 'https://bedivere-sun.github.io'
locale = 'zh-CN'
title = 'Bedivere 的 Blog'
theme = 'rusty-typewriter'

[params]
  author = 'Bedivere'
  description = '我的Hugo个人博客，最小说Github Pages搭建！'



[params.rtwt]
  sidePane = true
  countPageItems = 7

[params.rtwt.home]
  showBio = true
  showAuthorImg = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

[params.rtwt.side.home]
  sidePaneSticky = false
  taxonomies = ['tags']
  countTaxonomy = 5

[params.rtwt.side.single]
  sidePaneSticky = true
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5
